// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: MyService/mymicroservice.proto

package MyService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type ReplayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MyService_mymicroservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MyService_mymicroservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_MyService_mymicroservice_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The responce message containing the string and number
type Replay1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Replay1) Reset() {
	*x = Replay1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MyService_mymicroservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replay1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replay1) ProtoMessage() {}

func (x *Replay1) ProtoReflect() protoreflect.Message {
	mi := &file_MyService_mymicroservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replay1.ProtoReflect.Descriptor instead.
func (*Replay1) Descriptor() ([]byte, []int) {
	return file_MyService_mymicroservice_proto_rawDescGZIP(), []int{1}
}

func (x *Replay1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_MyService_mymicroservice_proto protoreflect.FileDescriptor

var file_MyService_mymicroservice_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x4d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x79, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x6d, 0x79, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x31,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x53, 0x0a, 0x09, 0x4d, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x53, 0x61, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x61, 0x79, 0x31, 0x12, 0x1d, 0x2e, 0x6d, 0x79, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x79, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x79, 0x31, 0x22, 0x00, 0x42,
	0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x73,
	0x73, 0x65, 0x72, 0x67, 0x65, 0x69, 0x2f, 0x4d, 0x79, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f,
	0x4d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_MyService_mymicroservice_proto_rawDescOnce sync.Once
	file_MyService_mymicroservice_proto_rawDescData = file_MyService_mymicroservice_proto_rawDesc
)

func file_MyService_mymicroservice_proto_rawDescGZIP() []byte {
	file_MyService_mymicroservice_proto_rawDescOnce.Do(func() {
		file_MyService_mymicroservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_MyService_mymicroservice_proto_rawDescData)
	})
	return file_MyService_mymicroservice_proto_rawDescData
}

var file_MyService_mymicroservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_MyService_mymicroservice_proto_goTypes = []interface{}{
	(*ReplayRequest)(nil), // 0: mymicroservice.ReplayRequest
	(*Replay1)(nil),       // 1: mymicroservice.Replay1
}
var file_MyService_mymicroservice_proto_depIdxs = []int32{
	0, // 0: mymicroservice.MyService.SayReplay1:input_type -> mymicroservice.ReplayRequest
	1, // 1: mymicroservice.MyService.SayReplay1:output_type -> mymicroservice.Replay1
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_MyService_mymicroservice_proto_init() }
func file_MyService_mymicroservice_proto_init() {
	if File_MyService_mymicroservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MyService_mymicroservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MyService_mymicroservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replay1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MyService_mymicroservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MyService_mymicroservice_proto_goTypes,
		DependencyIndexes: file_MyService_mymicroservice_proto_depIdxs,
		MessageInfos:      file_MyService_mymicroservice_proto_msgTypes,
	}.Build()
	File_MyService_mymicroservice_proto = out.File
	file_MyService_mymicroservice_proto_rawDesc = nil
	file_MyService_mymicroservice_proto_goTypes = nil
	file_MyService_mymicroservice_proto_depIdxs = nil
}
